Step 1 - Step 2
akimov228aleksei/DRF pull request #1
Opened 2022-03-11 14:40 UTC by akimov228aleksei

Documentation created, gitignore file added.

2022-03-11 15:52 UTC, jimmyhollywood requested changes
1. Rename PR title according to contained changes
2. Fix comments in review

2022-03-11 15:52 UTC, jimmyhollywood commented on docs/SRS.md
> +       ![](https://i.imgur.com/4TH6N0W.png)
Let's upload all images to the repository in `/docs/img` or something like that

2022-03-11 15:52 UTC, jimmyhollywood commented on docs/SRS.md
> +       For security reasons, some functions are not available for certain categories of users:
I suggest using roles. Admin, moderator or manager and employee.
Admin should have all privileges - read/write.
Moderator/manager should have write permissions - which means read/add/edit/delete.
Employee should only have read permissions.

Note: Any user should not have access to the system until authorization.

2022-03-11 15:52 UTC, jimmyhollywood commented on docs/SRS.md
> +- # Introduction
Why are you using dashes and plus signs in headers?

There is an example of using of markdown elements:

# Header 1

## Topic 1

Some text

## Topic 2

Enumeration:
- Item 1
- Item 2

# Header 2

etc...

2022-03-11 17:07 UTC, akimov228aleksei commented on docs/SRS.md
> +       ![](https://i.imgur.com/4TH6N0W.png)
Fixed

2022-03-11 17:07 UTC, akimov228aleksei commented on docs/SRS.md
> +       For security reasons, some functions are not available for certain categories of users:
Fixed

2022-03-11 17:07 UTC, akimov228aleksei commented on docs/SRS.md
> +- # Introduction
Fixed

2022-03-14 08:29 UTC, jimmyhollywood approved these changes

2022-03-14 09:47 UTC, merged