Step 5. Data models defined
akimov228aleksei/DRF pull request #4
Opened 2022-03-18 09:33 UTC by akimov228aleksei

Models have been created.

2022-03-18 12:27 UTC, jimmyhollywood requested changes

2022-03-18 12:27 UTC, jimmyhollywood commented on src/management/backend/DAO.py
> +"""The file contains all the available methods
At this step we do not need DAO layer

2022-03-18 12:27 UTC, jimmyhollywood commented on src/management/backend/models/department.py
> +    def amount(self):
Please, use more obvious name for this method

2022-03-18 12:27 UTC, jimmyhollywood commented on src/management/backend/models/department.py
> +        from backend.DAO import EmployeeDAO
Model mustn't depend on DAO layer. If you need to count number of employees then use sql count statement (see in django docs) or any other option

2022-03-18 12:27 UTC, jimmyhollywood commented on src/management/backend/models/department.py
> +        from backend.DAO import EmployeeDAO
The same. One more - imports in the middle of the code - it is not a good idea

2022-03-18 15:38 UTC, akimov228aleksei commented on src/management/backend/DAO.py
> +"""The file contains all the available methods
Deleted.

2022-03-18 15:38 UTC, akimov228aleksei commented on src/management/backend/models/department.py
> +    def amount(self):
Renamed.

2022-03-18 15:38 UTC, akimov228aleksei commented on src/management/backend/models/department.py
> +        from backend.DAO import EmployeeDAO
Fixed.

2022-03-18 15:38 UTC, akimov228aleksei commented on src/management/backend/models/department.py
> +        from backend.DAO import EmployeeDAO
Fixed.

2022-03-18 19:07 UTC, jimmyhollywood commented on src/management/backend/models/department.py
> +        from backend.DAO import EmployeeDAO
Not yet. Please read closely documentation fro models in django and aggregation

2022-03-19 10:02 UTC, akimov228aleksei commented on src/management/backend/models/department.py
> +        from backend.DAO import EmployeeDAO
I hope I've corrected it now

2022-03-21 15:09 UTC, jimmyhollywood requested changes

2022-03-21 15:09 UTC, jimmyhollywood commented on src/management/backend/models/department.py
> +        count = Employee.objects.values('department_id').annotate(employee=Count('id')).filter(department_id=self.pk)
Look into the https://docs.djangoproject.com/en/4.0/topics/db/aggregation/#generating-aggregates-for-each-item-in-a-queryset
Maybe it is possible to simplify the request

2022-03-21 19:31 UTC, akimov228aleksei commented on src/management/backend/models/department.py
> +        count = Employee.objects.values('department_id').annotate(employee=Count('id')).filter(department_id=self.pk)
Simplified this query

2022-03-22 10:30 UTC, jimmyhollywood approved these changes
Fix count query for department according to link I added and then merge without my approval

2022-03-22 10:30 UTC, jimmyhollywood commented on src/management/backend/models/department.py
> +        count = Department.objects.annotate(Count('employee')).filter(pk=self.pk)
Why do you need here filtering? There is a pretty simply way to get number of foreign key references - https://docs.djangoproject.com/en/4.0/ref/models/querysets/#annotate

2022-03-22 10:30 UTC, jimmyhollywood commented on src/management/backend/models/department.py
> +        salary = Employee.objects.values('department_id').annotate(salary=Avg('salary')).filter(department_id=self.pk)
Let's leave this as is but you definitely have to refactor this part. Let's maybe create an issue in github Issues tab for this and will return to that later

2022-03-24 11:39 UTC, merged