Step 6.2 Develop backend (API) part.
akimov228aleksei/DRF pull request #6
Opened 2022-04-29 09:14 UTC by akimov228aleksei

- Created fixtures.
- Added quick start in README.
- Updated DB settings.

2022-05-04 09:54 UTC, jimmyhollywood requested changes

2022-05-04 09:54 UTC, jimmyhollywood commented on src/management/Makefile
> +	python -m pip install -U pip
Please, fix the formatting

2022-05-04 09:54 UTC, jimmyhollywood commented on src/management/Makefile
> +				python ./manage.py makemigrations
One of the features of using Makefiles is that you can combine multiple commands -- here two latest lines seems like a duplication of `run_migration` commands - so you can just call that command here

2022-05-04 09:54 UTC, jimmyhollywood commented on src/management/Makefile
> +				python ./manage.py makemigrations
And just wondering -- what the purpose of this command?

2022-05-04 09:54 UTC, jimmyhollywood commented on README.md
> +    1. Define invironment variables for DB (or use default variables)
Describe here the list of the env variables

2022-05-04 09:54 UTC, jimmyhollywood commented on src/management/Makefile
> +run_server:
This looks a bit confusing for me -- the command name is `run_server` but it does a lot work outside the scope based on the title.
`run_server` have to simply run the web server =)
I think it is reasonable to add a separate command to initialize the application. Let say `init_app` command should install the python packages, run migration and load fixtures

2022-05-04 11:03 UTC, akimov228aleksei commented on src/management/Makefile
> +	python -m pip install -U pip
Fixed

2022-05-04 11:10 UTC, akimov228aleksei commented on src/management/Makefile
> +				python ./manage.py makemigrations
`reset_sqlite` is command which repeat `reset_db` command, but `reset_sqlite` also delete sqlite.db file. It is helpful when you use sqlite3 database and want to reset db.

2022-05-04 11:11 UTC, akimov228aleksei commented on src/management/Makefile
> +run_server:
Fixed.

2022-05-04 11:32 UTC, akimov228aleksei commented on README.md
> +    1. Define invironment variables for DB (or use default variables)
Fixed.

2022-05-05 07:40 UTC, jimmyhollywood approved these changes

2022-05-05 08:08 UTC, merged